### ISSUE TITLE
post (final) results to gitter

### ISSUE THREAD

**Issue by ghost** [coq/coq-bench#14]

**Comment by maximedenes** [comment]
This would be a dream :)

**Comment by JasonGross** [comment]
I'm not sure how to make things show up in the chat rather than in activity, but if we make sure that the script prints the final table at the end of the log, after everything else, and then change the log part of the configuration* to send however many lines we expect the table to be (and add a note somewhere that when you add more packages you should increase the log count), this would be almost what we want, right?

*Here:
![image](https://user-images.githubusercontent.com/396076/70369429-3b22a800-1887-11ea-9154-8b962d591d6a.png)

**Comment by JasonGross** [comment]
It looks like we could instead use the REST API to send messages, if we wanted to: https://developer.gitter.im/docs/rest-api

**Comment by ejgallego** [comment]
This was implemented by @SkySkimmer in https://github.com/coq/coq/pull/14323
