### ISSUE TITLE
Wrong options passed to configure

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq-bench#35]
@psteckler's job here failed https://ci.inria.fr/coq/view/opam/job/benchmark-part-of-the-branch/159/console because `./configure` is called with `-usecamlp5` and `-nodoc`. These options have been removed. `-nodoc` should be replaced with `-with-doc no`. `-usecamlp5` was a no-op and should simply be removed.

**Comment by ghost** [comment]
@Zimmi48
I have fixed the problem (for `coq.dev`) and [restarted](https://ci.inria.fr/coq/view/opam/job/benchmark-part-of-the-branch/160/console) the job Paul tried to run previously.

The changes are being tested.
(now with `coq.dev`; then I need to test the changes with `coq.8.7.dev`)

**Comment by Zimmi48** [comment]
Thanks! I'll let you close the issue whenever you have finished your testing.

**Comment by ghost** [comment]
The problem you reported is fixed. Benchmarking of branches based on Coq `master` [works again](https://ci.inria.fr/coq/view/opam/job/benchmark-part-of-the-branch/160/console).

There are many other problems to solve:
- define necessary OPAM packages so that we can do benchmarking with `coq.8.7.dev`
- go through the OPAM packages that we have and figure out why so many of them are no longer installable (compare what is being done by Travis and what do we have in `opam` recipes).
- ...

But that is another story.
