### ISSUE TITLE
shared/opam_install.sh is a heresy

### ISSUE THREAD

**Issue by maximedenes** [coq/coq-bench#5]
Correct me if I'm wrong, but with `shared/opam_install.sh`, if the network is down for 15 minutes, we'll get results without failures, but with a 15 minutes increment in the timings. That's a terrible idea, and that's probably what happend with fiat some time ago.

**Comment by ghost** [comment]
Good point.

**Comment by ghost** [comment]
Two things (at least) need to be done:
- avoid non-terminating loop in case of permanent network errors
- make sure that if transient network errors occur, the benchmarking time is not disturbed.

This is related to two problems:
- originally, when some of the `opam install` commands failed, the whole thing failed
- there is no direct way to separate the `download` action from the `build` and `install` actions

If they were separable, I could wrap the `download` action with a loop that would deal with transient networking problems so that we can measure the time of `build` independently from the time how long does it take to download a given thing. This is related to issue #1 .

**Comment by ghost** [comment]
This should be [fixed](https://github.com/coq/coq-bench/commit/7d1fd934d21252ba56417172c0ce2c77991a49ff) now.

My very rudimentary tests have finished. No gross errors were discovered with this commit.

**Comment by ghost** [comment]
I still use the _heretic_ `opam_install.sh` in those places where it is harmless, though.

**Comment by maximedenes** [comment]
> I still use the heretic opam_install.sh in those places where it is harmless, though.

:) You mean to install dependencies? It would be good to limit the number of attempts in any case (like 3).

**Comment by ghost** [comment]
Ok. I'll make that change.
